language: cpp
compiler:
  - clang
  - gcc
install: "./acprep dependencies"
before_script: "./acprep opt make --python"
script:
  - "./acprep check -- --output-on-failure"
  - "PYTHONPATH=. python python/demo.py"
notifications:
  email:
    on_success: change
    on_failure: change
  irc: "chat.freenode.net#ledger"
